name: PerPlayerDistance
version: '1.0'
main: MightyDevelopment.PerPlayerDistance
api-version: '1.21'
authors: [Im_Pishi]
softdepend: [LuckPerms, PlaceholderAPI]

commands:
  ppd:
    description: Per-player distance management
    usage: /ppd <set|reset|group|reload>
    permission: ppd.use
